from __future__ import annotations

from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from services.api.app.models import CanonicalPassage, CanonicalWork
from services.api.app.services.canonical_corpus import locator_sort_key, normalize_locator, source_authority_score


DEMO_WORKS: list[dict[str, Any]] = [
    {
        "work_key": "bhagavad_gita",
        "title_sa": "Bhagavad Gita",
        "title_hi": "Bhagavad Gita",
        "title_en": "Bhagavad Gita",
        "category": "gita",
        "tradition_scope": ["vaidika", "yoga", "vedanta"],
        "authority_level": "PRIMARY",
        "canonical_status": "VERIFIED",
        "metadata_json": {"seed": "demo", "rights_basis": "public_domain_review_required"},
    },
    {
        "work_key": "isha_upanishad",
        "title_sa": "Isha Upanishad",
        "title_hi": "Isha Upanishad",
        "title_en": "Isha Upanishad",
        "category": "upanishad",
        "tradition_scope": ["vaidika", "vedanta"],
        "authority_level": "PRIMARY",
        "canonical_status": "VERIFIED",
        "metadata_json": {"seed": "demo", "rights_basis": "public_domain_review_required"},
    },
    {
        "work_key": "katha_upanishad",
        "title_sa": "Katha Upanishad",
        "title_hi": "Katha Upanishad",
        "title_en": "Katha Upanishad",
        "category": "upanishad",
        "tradition_scope": ["vaidika", "vedanta"],
        "authority_level": "PRIMARY",
        "canonical_status": "VERIFIED",
        "metadata_json": {"seed": "demo", "rights_basis": "public_domain_review_required"},
    },
    {
        "work_key": "mundaka_upanishad",
        "title_sa": "Mundaka Upanishad",
        "title_hi": "Mundaka Upanishad",
        "title_en": "Mundaka Upanishad",
        "category": "upanishad",
        "tradition_scope": ["vaidika", "vedanta"],
        "authority_level": "PRIMARY",
        "canonical_status": "VERIFIED",
        "metadata_json": {"seed": "demo", "rights_basis": "public_domain_review_required"},
    },
    {
        "work_key": "yoga_sutra",
        "title_sa": "Yoga Sutra",
        "title_hi": "Yoga Sutra",
        "title_en": "Yoga Sutra",
        "category": "yoga",
        "tradition_scope": ["yoga", "darshana"],
        "authority_level": "PRIMARY",
        "canonical_status": "VERIFIED",
        "metadata_json": {"seed": "demo", "rights_basis": "public_domain_review_required"},
    },
    {
        "work_key": "dhammapada",
        "title_sa": "Dhammapada",
        "title_hi": "Dhammapada",
        "title_en": "Dhammapada",
        "category": "buddhist",
        "tradition_scope": ["bauddha", "ethics"],
        "authority_level": "PRIMARY",
        "canonical_status": "VERIFIED",
        "metadata_json": {"seed": "demo", "rights_basis": "public_domain_review_required"},
    },
]


DEMO_PASSAGES: list[dict[str, Any]] = [
    {
        "work_key": "bhagavad_gita",
        "locator": "2.47",
        "sanskrit_text": "karmany evadhikaras te ma phalesu kadacana",
        "normalized_text": "You have a claim over action, not over the fruits of action.",
        "translation_hi": "Karma par adhikar hai, phal par asakti nahi.",
        "translation_en": "Your responsibility is action, without attachment to its result.",
        "chapter": "2",
        "verse": "47",
        "confidence": 0.92,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "bhagavad_gita",
        "locator": "4.7",
        "sanskrit_text": "yada yada hi dharmasya glanir bhavati bharata",
        "normalized_text": "Whenever dharma declines, restoration becomes necessary.",
        "translation_hi": "Jab jab dharma ki glani hoti hai, tab samyak sthapana ki avashyakta hoti hai.",
        "translation_en": "When dharma declines, restoration of order is required.",
        "chapter": "4",
        "verse": "7",
        "confidence": 0.88,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "bhagavad_gita",
        "locator": "2.48",
        "sanskrit_text": "yoga-sthah kuru karmani sangam tyaktva dhananjaya",
        "normalized_text": "Act from steadiness in yoga, leaving attachment to success and failure.",
        "translation_hi": "Samatva me sthit hokar karma karo; safalta-asafalta se chipko nahi.",
        "translation_en": "Perform action from inner steadiness, without clinging to outcomes.",
        "chapter": "2",
        "verse": "48",
        "confidence": 0.91,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "bhagavad_gita",
        "locator": "3.19",
        "sanskrit_text": "tasmad asaktah satatam karyam karma samacara",
        "normalized_text": "Do the work that ought to be done without attachment.",
        "translation_hi": "Jo kartavya hai use asakti ke bina nirantar karo.",
        "translation_en": "One should perform necessary duty without attachment.",
        "chapter": "3",
        "verse": "19",
        "confidence": 0.9,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "bhagavad_gita",
        "locator": "4.8",
        "sanskrit_text": "paritranaya sadhunam vinasaya ca duskrtam",
        "normalized_text": "Dharma is restored by protecting the good and correcting destructive force.",
        "translation_hi": "Dharma ki sthapana sadhu-raksha aur adharm ke niyantran se hoti hai.",
        "translation_en": "Restoration of dharma includes protection, correction, and renewal.",
        "chapter": "4",
        "verse": "8",
        "confidence": 0.88,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "bhagavad_gita",
        "locator": "6.5",
        "sanskrit_text": "uddhared atmanatmanam natmanam avasadayet",
        "normalized_text": "A person should lift the self by the self and not degrade the self.",
        "translation_hi": "Vyakti ko apne vivek se apne aap ko uthana chahiye, girana nahi.",
        "translation_en": "Self-mastery begins by raising oneself through disciplined awareness.",
        "chapter": "6",
        "verse": "5",
        "confidence": 0.9,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "bhagavad_gita",
        "locator": "6.26",
        "sanskrit_text": "yato yato niscalati manas cancalam asthiram",
        "normalized_text": "Whenever the restless mind wanders, bring it back under the self.",
        "translation_hi": "Jab man bhatakta hai, use dhairya se wapas sthirata me lao.",
        "translation_en": "The wandering mind is repeatedly returned to steadiness.",
        "chapter": "6",
        "verse": "26",
        "confidence": 0.89,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "bhagavad_gita",
        "locator": "12.13",
        "sanskrit_text": "adveshta sarva-bhutanam maitrah karuna eva ca",
        "normalized_text": "The mature devotee is free from hatred, friendly and compassionate to beings.",
        "translation_hi": "Pakva bhakta dvesh se mukt, mitra-bhava aur karuna se yukt hota hai.",
        "translation_en": "Devotion is shown through non-hatred, friendliness, and compassion.",
        "chapter": "12",
        "verse": "13",
        "confidence": 0.89,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "bhagavad_gita",
        "locator": "12.14",
        "sanskrit_text": "santustah satatam yogi yatatma drdha-niscayah",
        "normalized_text": "A disciplined person is steady, content, self-governed, and firmly resolved.",
        "translation_hi": "Yogi santusht, sanyamit, sthir aur dridh sankalp wala hota hai.",
        "translation_en": "The path values contentment, discipline, steadiness, and resolve.",
        "chapter": "12",
        "verse": "14",
        "confidence": 0.88,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "isha_upanishad",
        "locator": "1",
        "sanskrit_text": "isavasyam idam sarvam",
        "normalized_text": "All this is pervaded by the divine.",
        "translation_hi": "Yah sampurna jagat ishavasyam hai.",
        "translation_en": "All existence is pervaded by the divine reality.",
        "section": "mantra",
        "verse": "1",
        "confidence": 0.9,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "isha_upanishad",
        "locator": "2",
        "sanskrit_text": "kurvann eveha karmani jijivisec chatam samah",
        "normalized_text": "One may live fully while performing action in the right spirit.",
        "translation_hi": "Sahi bhava se karma karte hue jeevan ko poornata se jiya ja sakta hai.",
        "translation_en": "Life is not rejected; action is purified by right understanding.",
        "section": "mantra",
        "verse": "2",
        "confidence": 0.88,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "isha_upanishad",
        "locator": "6",
        "sanskrit_text": "yas tu sarvani bhutany atmany evanupasyati",
        "normalized_text": "One who sees all beings in the self does not fall into separation.",
        "translation_hi": "Jo sab bhuton ko atma me dekhta hai, vah bhed-bhava me nahi girta.",
        "translation_en": "Seeing beings in the self loosens alienation and hatred.",
        "section": "mantra",
        "verse": "6",
        "confidence": 0.87,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "isha_upanishad",
        "locator": "7",
        "sanskrit_text": "yasmin sarvani bhutany atmaivabhud vijanatah",
        "normalized_text": "For the knower, all beings are understood through the unity of self.",
        "translation_hi": "Jnanavan ke liye sab me ek atma-bhava prakat hota hai.",
        "translation_en": "Knowledge reveals a unity that changes how one relates to all beings.",
        "section": "mantra",
        "verse": "7",
        "confidence": 0.87,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "katha_upanishad",
        "locator": "1.2.1",
        "sanskrit_text": "sreyas ca preyas ca manusyam etas",
        "normalized_text": "The beneficial and the merely pleasant both approach a human being.",
        "translation_hi": "Manushya ke saamne shreyas aur preyas dono aate hain.",
        "translation_en": "A key human choice is between what is truly beneficial and what is only pleasant.",
        "section": "1.2",
        "verse": "1",
        "confidence": 0.89,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "katha_upanishad",
        "locator": "1.2.2",
        "sanskrit_text": "sreyo hi dhiro abhi preyaso vrnite",
        "normalized_text": "The wise choose the beneficial over the merely pleasant.",
        "translation_hi": "Dheera vyakti preyas ke bajay shreyas ko chunta hai.",
        "translation_en": "Wisdom prefers long-term good over immediate attraction.",
        "section": "1.2",
        "verse": "2",
        "confidence": 0.9,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "katha_upanishad",
        "locator": "1.3.3",
        "sanskrit_text": "atmanam rathinam viddhi sariram ratham eva tu",
        "normalized_text": "The self is the rider and the body is compared to a chariot.",
        "translation_hi": "Atma ko rathi aur sharir ko rath ke roop me samjho.",
        "translation_en": "The chariot image explains self, body, mind, senses, and discipline.",
        "section": "1.3",
        "verse": "3",
        "confidence": 0.88,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "katha_upanishad",
        "locator": "1.3.14",
        "sanskrit_text": "uttisthata jagrata prapya varan nibodhata",
        "normalized_text": "Arise, awaken, and learn from the wise.",
        "translation_hi": "Utho, jago, aur gyani se samajh prapt karo.",
        "translation_en": "The seeker is urged to wake up and seek clear understanding.",
        "section": "1.3",
        "verse": "14",
        "confidence": 0.91,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "mundaka_upanishad",
        "locator": "1.1.4",
        "sanskrit_text": "dve vidye veditavye para caivapara ca",
        "normalized_text": "Two kinds of knowledge are to be known: higher and lower.",
        "translation_hi": "Do prakaar ki vidya kahi gayi hai: para aur apara.",
        "translation_en": "The text distinguishes instrumental knowledge from liberating knowledge.",
        "section": "1.1",
        "verse": "4",
        "confidence": 0.89,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "mundaka_upanishad",
        "locator": "2.2.5",
        "sanskrit_text": "satyena labhyas tapasa hy esa atma",
        "normalized_text": "The self is realized through truthfulness, discipline, and clear knowledge.",
        "translation_hi": "Satya, tapas aur spasht jnan se atma ka bodh hota hai.",
        "translation_en": "Truthfulness and disciplined clarity are central to realization.",
        "section": "2.2",
        "verse": "5",
        "confidence": 0.86,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "mundaka_upanishad",
        "locator": "3.1.6",
        "sanskrit_text": "satyam eva jayate nanrtam",
        "normalized_text": "Truth alone prevails, not falsehood.",
        "translation_hi": "Satya hi vijayi hota hai, asatya nahi.",
        "translation_en": "The passage affirms truth as the enduring path.",
        "section": "3.1",
        "verse": "6",
        "confidence": 0.91,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "yoga_sutra",
        "locator": "1.2",
        "sanskrit_text": "yogas citta-vrtti-nirodhah",
        "normalized_text": "Yoga is the stilling and regulation of the movements of the mind.",
        "translation_hi": "Yoga chitta ki vrittiyon ko sthir aur niyantrit karna hai.",
        "translation_en": "Yoga is mental discipline that quiets reactive patterns.",
        "section": "samadhi pada",
        "verse": "2",
        "confidence": 0.91,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "yoga_sutra",
        "locator": "1.12",
        "sanskrit_text": "abhyasa-vairagyabhyam tan-nirodhah",
        "normalized_text": "The mind is steadied by practice and non-attachment.",
        "translation_hi": "Abhyas aur vairagya se man sthir hota hai.",
        "translation_en": "Practice and non-attachment work together in yoga.",
        "section": "samadhi pada",
        "verse": "12",
        "confidence": 0.9,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "yoga_sutra",
        "locator": "1.33",
        "sanskrit_text": "maitri-karuna-muditopeksanam sukha-duhkha-punyapunya-visayanam",
        "normalized_text": "Friendliness, compassion, joy, and equanimity help purify the mind.",
        "translation_hi": "Maitri, karuna, mudita aur upeksha se chitta prasanna hota hai.",
        "translation_en": "Relational virtues support mental clarity and peace.",
        "section": "samadhi pada",
        "verse": "33",
        "confidence": 0.88,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "yoga_sutra",
        "locator": "2.29",
        "sanskrit_text": "yama-niyama-asana-pranayama-pratyahara-dharana-dhyana-samadhayo astav angani",
        "normalized_text": "Yoga has eight limbs: restraints, observances, posture, breath, withdrawal, concentration, meditation, and absorption.",
        "translation_hi": "Yoga ke aath ang yama, niyama, asana, pranayama, pratyahara, dharana, dhyana aur samadhi hain.",
        "translation_en": "The eight-limbed path gives a practical structure for yoga discipline.",
        "section": "sadhana pada",
        "verse": "29",
        "confidence": 0.9,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "dhammapada",
        "locator": "1",
        "sanskrit_text": "mano pubbangama dhamma",
        "normalized_text": "Mind precedes experience; intention shapes conduct and its result.",
        "translation_hi": "Man pradhan hai; sankalp vyavahar aur phal ko akar deta hai.",
        "translation_en": "The mind is primary in shaping action and consequence.",
        "section": "yamaka vagga",
        "verse": "1",
        "confidence": 0.86,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "dhammapada",
        "locator": "5",
        "sanskrit_text": "na hi verena verani sammantidha kudacanam",
        "normalized_text": "Hatred is not ended by hatred; it is ended by non-hatred.",
        "translation_hi": "Dvesh se dvesh shant nahi hota; advesh se hota hai.",
        "translation_en": "Hostility is not resolved by more hostility.",
        "section": "yamaka vagga",
        "verse": "5",
        "confidence": 0.88,
        "review_status": "VERIFIED",
    },
    {
        "work_key": "dhammapada",
        "locator": "183",
        "sanskrit_text": "sabba papassa akaranam kusalassa upasampada",
        "normalized_text": "Avoid wrongdoing, cultivate the wholesome, and purify the mind.",
        "translation_hi": "Pap se bacho, kushal ko badhao, aur man ko shuddh karo.",
        "translation_en": "The path is ethical restraint, wholesome cultivation, and mental purification.",
        "section": "buddha vagga",
        "verse": "183",
        "confidence": 0.88,
        "review_status": "VERIFIED",
    },
]


async def seed_demo_canonical(session: AsyncSession) -> dict[str, Any]:
    work_key_to_id: dict[str, str] = {}
    inserted_works = 0
    inserted_passages = 0

    for payload in DEMO_WORKS:
        result = await session.execute(select(CanonicalWork).where(CanonicalWork.work_key == payload["work_key"]))
        row = result.scalars().first()
        if row is None:
            row = CanonicalWork(**payload)
            session.add(row)
            await session.flush()
            inserted_works += 1
        work_key_to_id[row.work_key] = row.id

    for payload in DEMO_PASSAGES:
        work_id = work_key_to_id[payload["work_key"]]
        locator = normalize_locator(payload["locator"])
        result = await session.execute(
            select(CanonicalPassage).where(
                CanonicalPassage.work_id == work_id,
                CanonicalPassage.locator == locator,
            )
        )
        if result.scalars().first() is not None:
            continue
        passage_payload = {key: value for key, value in payload.items() if key != "work_key"}
        work = await session.get(CanonicalWork, work_id)
        row = CanonicalPassage(
            **{key: value for key, value in passage_payload.items() if key != "locator"},
            work_id=work_id,
            locator=locator,
            locator_sort_key=locator_sort_key(locator),
            source_ids=[],
            authority_score=source_authority_score(
                work.authority_level if work else "PRIMARY",
                passage_payload.get("review_status", "VERIFIED"),
                passage_payload.get("confidence", 0.9),
            ),
            metadata_json={"seed": "demo"},
        )
        session.add(row)
        inserted_passages += 1

    await session.commit()
    return {
        "imported": {"works": inserted_works, "passages": inserted_passages},
        "totals": {"works": len(DEMO_WORKS), "passages": len(DEMO_PASSAGES)},
    }
