from enum import StrEnum


class RightsStatus(StrEnum):
    PUBLIC_DOMAIN_VERIFIED = "PUBLIC_DOMAIN_VERIFIED"
    LICENSED_VERIFIED = "LICENSED_VERIFIED"
    OPEN_LICENSE_VERIFIED = "OPEN_LICENSE_VERIFIED"
    USER_OWNED = "USER_OWNED"
    REFERENCE_ONLY = "REFERENCE_ONLY"
    NO_TRAINING_ALLOWED = "NO_TRAINING_ALLOWED"
    NO_STORAGE_ALLOWED = "NO_STORAGE_ALLOWED"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"


class IngestionStatus(StrEnum):
    INGESTED = "INGESTED"
    PARSED = "PARSED"
    NORMALIZED = "NORMALIZED"
    CHUNKED = "CHUNKED"
    EMBEDDED = "EMBEDDED"
    INDEXED = "INDEXED"
    REVIEW_PENDING = "REVIEW_PENDING"
    APPROVED_Z1 = "APPROVED_Z1"
    APPROVED_Z2 = "APPROVED_Z2"
    BLOCKED = "BLOCKED"
    DEPRECATED = "DEPRECATED"


class ArtifactType(StrEnum):
    MODEL = "MODEL"
    RAG_INDEX = "RAG_INDEX"
    DATASET = "DATASET"
    ONTOLOGY = "ONTOLOGY"
    BENCHMARK = "BENCHMARK"
    PROMPT_PACK = "PROMPT_PACK"
    CONTENT_BATCH = "CONTENT_BATCH"
    CONTENT_EXPORT = "CONTENT_EXPORT"


class Severity(StrEnum):
    P0 = "P0"
    P1 = "P1"
    P2 = "P2"
    P3 = "P3"


class ContentBatchStatus(StrEnum):
    DRAFT = "DRAFT"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ContentReviewStatus(StrEnum):
    REVIEW_PENDING = "REVIEW_PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    NEEDS_REVISION = "NEEDS_REVISION"
    AUTO_BLOCKED = "AUTO_BLOCKED"


class ExportFormat(StrEnum):
    JSONL = "jsonl"
    MARKDOWN = "markdown"
    CSV = "csv"
